apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  valuesContent: |-
    rbac:
      enabled: true
    ssl:
      enabled: true
      enforced: true
      permanentRedirect: true
    metrics:
      prometheus:
        enabled: true
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    image: "rancher/library-traefik"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    serviceType: NodePort
    service:
      nodePorts:
        http: xxxxx # custom nodeport
        https: xxxxx # custom nodeport
    dashboard:
      enabled: true
      domain: "traefik.mydomain.com"
      auth:
        basic:
          admin: xxxxxxxxxxxxxx # the admin htpasswd you just generated
    acme:
      enabled: true
      logging: true
      staging: false
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      email: xxxxxxxxxxxxxx  # your email
      challengeType: "dns-01"
      dnsProvider:
        name: gcloud
        gcloud:
          GCE_PROJECT: "xxxxxxxxxxxxxx" # your Google Cloud Project
          GCE_SERVICE_ACCOUNT_FILE: "/secrets/gcloud-credentials.json"
      domains:
        enabled: true
        domainsList:
          - main: "*.mydomain.com"
          - sans:
            - "mydomain.com"
    secretFiles:
      gcloud-credentials.json: '{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}'